title: Wayne Stilwell
description: > # this means to ignore newlines until "baseurl:"
  Personal blog and website for web developer Wayne Stilwell.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://waynestilwell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: waynestilwell #if your site has a twitter account, enter it here

# Author Settings
author: Wayne Stilwell # add your name
author-img: me.png # add your photo
about-author: Dad, military husband, and software developer trying to stay up with the times. # add description
social-twitter: waynestilwell # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: waynestilwell # add your Github handle
social-linkedin: waynestilwell # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
